// Deokario's dynamic light widget configuration. Do NOT change this file, unless you know what are you doing.

[LightShapes]
Wall1=
Wall2=
Wall3=
Wall4=
FakeWall=
Wood=
Fire=
Generator=
Furnace=
DoorLeft=
DoorRight=
DoorTop=
DoorBottom=
CampfireDoor=
Blackhole=
ControlPoint=

[LightTypes]
Wall1=IN
Wall2=IN
Wall3=IN
Wall4=IN
FakeWall=IN
Wood=IN
Fire=OUT
Generator=IN
Furnace=OUT
DoorLeft=IN
DoorRight=IN
DoorTop=IN
DoorBottom=IN
CampfireDoor=IN
Blackhole=OUT
ControlPoint=OUT

[LightWeights]
Wall1=120
Wall2=120
Wall3=120
Wall4=120
FakeWall=120
Wood=120
Fire=120
Generator=120
Furnace=120
DoorLeft=120
DoorRight=120
DoorTop=120
DoorBottom=120
CampfireDoor=120
Blackhole=120
ControlPoint=120

[LightRGBs]
Fire=255,215,0
DoorLeft=255,0,0
DoorRight=0,0,255
DoorTop=0,255,0
DoorBottom=255,255,0
CampfireDoor=255,255,255
Blackhole=255,255,255
ControlPoint=0,255,255

[LightAutoShape]
sprites\world\wall_1.png
sprites\world\wall_2.png
sprites\world\wall_3.png
sprites\world\wall_4.png
sprites\world\fake_wall.png
sprites\world\campfire_wood.png
sprites\world\fire.png
sprites\world\generator\idle.png
sprites\world\left_door.png
sprites\world\right_door.png
sprites\world\top_door.png
sprites\world\bottom_door.png
sprites\world\campfire_door.png
sprites\entities\blackhole.png
sprites\world\cp\idle.png
sprites\world\furnace.png